### ISSUE TITLE
GWT Code Generator (non-numeric) generates bindings on numbers for enums

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hanson-opus/protostuff#19]
```
What steps will reproduce the problem?
1. Create a protobuf message with an enum
2. Generate the GWT binding (non-numeric)
3. The generated enum class uses the field numbers only

What is the expected output? What do you see instead?

I would expect the generated enum class to use the enum's name to map the
enum instances instead of the enum's field number.

What version of the product are you using? On what operating system?

1.0.0.M1

```

Original issue reported on code.google.com by `philippe...@gmail.com` on 7 Jun 2010 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
It is actually the expected output.
The protobuf enums are always serialized according to their value (declared in 
.proto) as a variable int.
Its the same behavior when you're serializing to protobuf, json and xml.

Hope that clears things up.
Thanks
```

Original comment by `david.yu...@gmail.com` on 8 Jun 2010 at 5:18
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
I'm using the protobuf-java-format JsonFormat to serialize my Message 
instances. We do this to be as close as possible to the protobuf tooling (it 
doesn't define additional artifacts for serialization).

The JsonFormat class serializes enums using their names. See here: 
http://code.google.com/p/protobuf-java-format/source/browse/trunk/protobuf-java-
format/src/java/com/google/protobuf/JsonFormat.java#230

By specifying non-numeric GWT binding, I had expected that every field be 
serialized using their name. I had also expected that the enum's value would be 
using the enum name (which is what JsonFormat expects also).
```

Original comment by `philippe...@gmail.com` on 8 Jun 2010 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
You can try the plugin compiler for your customization.
See http://code.google.com/p/protostuff/wiki/WritingCustomCodeGenerators

Basically create a custom_gwt_overlay.java.stg file and use it as the compiler 
output.

Subclass the gwt_overlay template and override the enum_block.

// header
group custom_gwt_overlay : gwt_overlay;

enum_block(eg, module, options, nested) ::= <<

// any reference to the number, change it to the name

>>




```

Original comment by `david.yu...@gmail.com` on 8 Jun 2010 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
Using r881

The custom template compiler fails if no "proto_block" template is defined in 
the file.

Is this really a requirement of custom templates?

Here's the stacktrace:
Caused by: java.lang.IllegalArgumentException: Can't find template 
proto_block.st; group hierarchy is [base]
    at org.antlr.stringtemplate.StringTemplateGroup.lookupTemplate(StringTemplateGroup.java:507)
    at org.antlr.stringtemplate.StringTemplateGroup.getInstanceOf(StringTemplateGroup.java:392)
    at org.antlr.stringtemplate.StringTemplateGroup.getInstanceOf(StringTemplateGroup.java:404)
    at org.antlr.stringtemplate.StringTemplateGroup.lookupTemplate(StringTemplateGroup.java:484)
    at org.antlr.stringtemplate.StringTemplateGroup.getInstanceOf(StringTemplateGroup.java:392)
    at org.antlr.stringtemplate.StringTemplateGroup.getInstanceOf(StringTemplateGroup.java:404)
    at org.antlr.stringtemplate.StringTemplateGroup.lookupTemplate(StringTemplateGroup.java:484)
    at org.antlr.stringtemplate.StringTemplateGroup.lookupTemplate(StringTemplateGroup.java:520)
    at com.dyuproject.protostuff.compiler.PluginProtoCompiler.<init>(PluginProtoCompiler.java:59)
    at com.dyuproject.protostuff.compiler.CompilerMain.compile(CompilerMain.java:172)
    at com.dyuproject.protostuff.mojo.ProtoCompilerMojo.execute(ProtoCompilerMojo.java:67)
    ... 19 more

```

Original comment by `philippe...@gmail.com` on 9 Jun 2010 at 6:28

**Comment by GoogleCodeExporter** [comment]
```
It is not a requirement.
Svn up ... should be ok now.

Cheers
```

Original comment by `david.yu...@gmail.com` on 10 Jun 2010 at 2:53
