### ISSUE TITLE
ArrayIndexOutOfBoundsException in StringSerializer.writeUTF8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hanson-opus/protostuff#27]
```
I'm seeing an ArrayIndexOutOfBoundsException in StringSerializer.writeUTF8.  

$ scala -classpath protostuff-api-1.0.0.M3.jar:protostuff-core-1.0.0.M3.jar 
crash.scala

java.lang.ArrayIndexOutOfBoundsException: 2047
        at com.dyuproject.protostuff.StringSerializer.writeUTF8(StringSerializer.java:462)
        at com.dyuproject.protostuff.StringSerializer.writeUTF8VarDelimited(StringSerializer.java:741)
        at com.dyuproject.protostuff.StringSerializer.writeUTF8VarDelimited(StringSerializer.java:883)
        at com.dyuproject.protostuff.BufferedOutput.writeString(BufferedOutput.java:206)
        at Main$$anon$1.<init>(crash.scala:15)
        at Main$.main(crash.scala:1)
        at Main.main(crash.scala)


crash.scala:

import com.dyuproject.protostuff._

def repeat(ch:Char, times:Int):String = {
  val sb = new StringBuilder
  (1 to times).foreach{i => sb.append(ch)}
  sb.toString
}

val bufferSize = 2048

val buffer = LinkedBuffer.allocate(bufferSize)
val output = new BufferedOutput(buffer, false/*encodeNestedMessageAsGroup*/)

output.writeString(1/*tag*/, repeat('a', bufferSize-6), false /*repeated*/)
output.writeString(2/*tag*/, repeat('a', bufferSize-2), false /*repeated*/)

```

Original issue reported on code.google.com by `timunder...@gmail.com` on 10 Sep 2010 at 8:32

Attachments:
- [crash.scala](https://storage.googleapis.com/google-code-attachments/protostuff/issue-27/comment-0/crash.scala)

**Comment by GoogleCodeExporter** [comment]
```
I think I figured it out.  In StringSerializer there is a bug when calculating 
the size of a new buffer when there isn't enough room in the current buffer for 
the varint size of the string.  The existing code seems to assume that the 
varint will only be 1 byte instead of using the expectedSize which breaks when 
it takes more than 1 byte for the length of the string and the length of the 
string is larger than the session.nextBufferSize.

Patch with Tests and attempted Fix attached and pasted below:

Index: 
protostuff-api/src/test/java/com/dyuproject/protostuff/StringSerializerTest.java
===================================================================
--- 
protostuff-api/src/test/java/com/dyuproject/protostuff/StringSerializerTest.java
    (revision 1012)
+++ 
protostuff-api/src/test/java/com/dyuproject/protostuff/StringSerializerTest.java
    (working copy)
@@ -145,7 +145,73 @@
         Double.MAX_VALUE,
         Double.MIN_VALUE
     };
-    
+
+    public void testVarDelimitedBoundryTwoByte() throws Exception
+    {
+        int size = 0x80+16; // takes 2 bytes for size
+
+        checkVarDelimitedBoundry(1, size);
+        checkVarDelimitedBoundry(2, size);
+        checkVarDelimitedBoundry(3, size);
+    }
+
+    public void testVarDelimitedBoundryThreeByte() throws Exception
+    {
+        int size = 0x800+16; // takes 3 bytes for size
+
+        checkVarDelimitedBoundry(1, size);
+        checkVarDelimitedBoundry(2, size);
+        checkVarDelimitedBoundry(3, size);
+        checkVarDelimitedBoundry(4, size);
+    }
+
+    public void testVarDelimitedBoundryFourByte() throws Exception
+    {
+        int size = 0x8000+16; // takes 4 bytes for size
+
+        checkVarDelimitedBoundry(1, size);
+        checkVarDelimitedBoundry(2, size);
+        checkVarDelimitedBoundry(3, size);
+        checkVarDelimitedBoundry(4, size);
+        checkVarDelimitedBoundry(5, size);
+    }
+
+    public void testVarDelimitedBoundryFiveByte() throws Exception
+    {
+        int size = 0x80000+16; // takes 5 bytes for size
+
+        checkVarDelimitedBoundry(1, size);
+        checkVarDelimitedBoundry(2, size);
+        checkVarDelimitedBoundry(3, size);
+        checkVarDelimitedBoundry(4, size);
+        checkVarDelimitedBoundry(5, size);
+        checkVarDelimitedBoundry(6, size);
+    }
+
+    public String repeatChar(char ch, int times)
+    {
+        StringBuilder sb = new StringBuilder(times);
+        for(int i = 0; i < times; i++)
+        {
+            sb.append(ch);
+        }
+        return sb.toString();
+    }
+
+    public void checkVarDelimitedBoundry(int initialGap, int secondWriteSize)
+    {
+        int bufferSize = 256;
+        final LinkedBuffer lb = LinkedBuffer.allocate(bufferSize);
+        WriteSession session = new WriteSession(lb, bufferSize);
+
+        // Should fill up the buffer with 1 byte left
+        StringSerializer.writeUTF8(repeatChar('a', bufferSize-initialGap), 
session, lb);
+
+        // Write a string that requires 3 bytes for the length and is larger
+        // than the next buffer size
+        StringSerializer.writeUTF8VarDelimited(repeatChar('a', 
secondWriteSize), session, lb);
+    }
+
     public void testInt() throws Exception
     {
         for(int i : int_targets)
Index: 
protostuff-api/src/main/java/com/dyuproject/protostuff/StringSerializer.java
===================================================================
--- 
protostuff-api/src/main/java/com/dyuproject/protostuff/StringSerializer.java    
    (revision 1012)
+++ 
protostuff-api/src/main/java/com/dyuproject/protostuff/StringSerializer.java    
    (working copy)
@@ -732,7 +732,7 @@
         {
             // not enough space for the varint.
             // create a new buffer.
-            lb = new LinkedBuffer(len+1 > session.nextBufferSize ? len+1 : 
session.nextBufferSize, 
+            lb = new LinkedBuffer(len+expectedSize > session.nextBufferSize ? 
len+expectedSize : session.nextBufferSize,
                     lb);
             offset = 0;
             lb.offset = expectedSize;
```

Original comment by `timunder...@gmail.com` on 10 Sep 2010 at 10:05

Attachments:
- [issue27.diff](https://storage.googleapis.com/google-code-attachments/protostuff/issue-27/comment-1/issue27.diff)

**Comment by GoogleCodeExporter** [comment]
```
Attached an updated patch to fix a test case (it wasn't properly testing for 
the condition) and fix some of the comments.
```

Original comment by `timunder...@gmail.com` on 10 Sep 2010 at 10:14

Attachments:
- [issue27.v2.diff](https://storage.googleapis.com/google-code-attachments/protostuff/issue-27/comment-2/issue27.v2.diff)

**Comment by GoogleCodeExporter** [comment]
```
Your patch has been applied. (rev 1017)
Thanks Tim!
```

Original comment by `david.yu...@gmail.com` on 11 Sep 2010 at 6:24
- Changed state: **Fixed**
