### ISSUE TITLE
RuntimeSchema.getSchema on Android

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hanson-opus/protostuff#67]
```
What steps will reproduce the problem?
1. Calling RuntimeSchema.getSchema on android application
2.
3.

What is the expected output? What do you see instead?
Create the schema object but get sun.reflect.ReflectionFactory no class 
definition error.

What version of the product are you using? On what operating system?
android 2.2

Please provide any additional information below.

```

Original issue reported on code.google.com by `pohzysg` on 16 May 2011 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
I solved this with the following:
@SuppressWarnings("unchecked")
    static <T> Constructor<T> getConstructor(Class<T> clazz)
    {
        try
        {
            return clazz.getConstructor((Class[])null);
        }
        catch (SecurityException e)
        {
            if(OBJECT_CONSTRUCTOR == null)
                throw new RuntimeException(e);

            try {
                return newInstanceSkippingConstructor(clazz); // changed this line with dumb exception handling
            } catch (Exception e1) {
                e1.printStackTrace();
                return null;
            }
        }
        catch (NoSuchMethodException e)
        {
            if(OBJECT_CONSTRUCTOR == null)
                throw new RuntimeException(e);

            try {
                return newInstanceSkippingConstructor(clazz); // changed this line with dumb exception handling
            } catch (Exception e1) {
                e1.printStackTrace();
                return null;
            }
        }
    }

    @SuppressWarnings("unchecked")
    static <T> Constructor<T> newInstanceSkippingConstructor(final Class<T> clazz) throws SecurityException, NoSuchMethodException, IllegalArgumentException, IllegalAccessException, InvocationTargetException {

        Method newInstance = ObjectInputStream.class.getDeclaredMethod("newInstance", Class.class, Class.class);
        newInstance.setAccessible(true);
        return (Constructor<T>) newInstance.invoke(null, clazz, Object.class);
    }
```

Original comment by `matyas.b...@gmail.com` on 7 Jun 2011 at 12:06

**Comment by GoogleCodeExporter** [comment]
```
Cool.  I saw that post too long ago :-)
http://stackoverflow.com/questions/3121515/is-it-possible-to-bypass-constructors
-when-instantiating-objects-in-android

Did you have any other android-specific problems?  
If not, we could certainly add that to protostuff-runtime for built-in android 
support.
```

Original comment by `david.yu...@gmail.com` on 27 Jun 2011 at 2:44
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Only using the CORE and API packages for now on android. Works very well with 
hand-created schema. Had not other issues with it.
```

Original comment by `matyas.b...@gmail.com` on 27 Jun 2011 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
Thanks for all the comments. By the way, now i am trying to build a 
hand-created schema, however whenever i tried to send a byte[] of around 900k 
using writeByteArray, it will display the following error
Caused by: com.dyuproject.protostuff.ProtobufException: While parsing a 
protocol message, the input ended unexpectedly in the middle of a field.  This 
could mean either than the input has been truncated or that an embedded message 
misreported its own length.
    at com.dyuproject.protostuff.ProtobufException.truncatedMessage(ProtobufException.java:73)
    ... 46 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at com.dyuproject.protostuff.ByteArrayInput.readByteArray(ByteArrayInput.java:346)
    at entity.UserAccountSchema.mergeFrom(UserAccountSchema.java:38)
    at entity.UserAccountSchema.mergeFrom(UserAccountSchema.java:19)
    at com.dyuproject.protostuff.IOUtil.mergeFrom(IOUtil.java:42)
    ... 45 more
Any inputs? Thanks in advance
```

Original comment by `pohzysg` on 30 Jun 2011 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Can you send me sample code that triggers this?  YOu can email it to me 
directly.
It would be faster for me to fix the issue.

Thanks
```

Original comment by `david.yu...@gmail.com` on 30 Jun 2011 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
My apologies. To clarify on the above error. it is happening on the server 
which is a restful web services.
Schema codes
 public void writeTo(Output output, UserAccount user) throws IOException {
       ......
        if (user.getData() != null) {
            output.writeByteArray(3, user.getData(), false);
        }
 public void mergeFrom(Input input, UserAccount user) throws IOException {
        while (true) {
            int number = input.readFieldNumber(this);
            switch (number) {
               .......
                case 3:
                    byte[] ars = input.readByteArray();
Android
        protostuff = ProtostuffIOUtil.toByteArray(userAccount, schema, buffer);
    httpput.setEntity(new StringEntity(new String(protostuff,"utf-8"), "utf-8"));
        result = httpclient.execute(httpput, handler);
Server
    @PUT
    @Consumes(MediaType.TEXT_PLAIN)
    public void putText(String content) {
            UserAccount accountNew = new UserAccount();
            LinkedBuffer buffer = LinkedBuffer.allocate(8192);
            Schema<UserAccount> schema = new UserAccountSchema();
            try {
                ProtostuffIOUtil.mergeFrom(content.getBytes("utf-8"), accountNew, schema);
            } finally {
                buffer.clear();
            }
    }

Hope that clarify the situation.Thanks a lot.
```

Original comment by `pohzysg` on 30 Jun 2011 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
To verify if the protostuff is culprit, verify on android:
protostuff = ProtostuffIOUtil.toByteArray(userAccount, schema, buffer);

UserAccount ua = new UserAccount();
ProtostuffIOUtil.mergeFrom(protostuff, ua, schema);
assertEquals(ua, userAccount);

If that works, then the problem is elsewhere.
It could be the transport, or the extra utf8 encoding of the http client, or 
the extra utf8 decoding of your http server.
```

Original comment by `david.yu...@gmail.com` on 30 Jun 2011 at 2:47

**Comment by GoogleCodeExporter** [comment]
```
I have sent the details to your personal email. Thanks.
```

Original comment by `pohzysg` on 30 Jun 2011 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
As discussed with pohzysg, his problem was not related to protostuff.

Matyas, I'm thinking of adding that snippet for protostuff-runtime to work 
effortlessly on android (now that the other compilation issue was fixed).
```

Original comment by `david.yu...@gmail.com` on 7 Jul 2011 at 9:39

**Comment by GoogleCodeExporter** [comment]
```
Here's a patch (pending commit) for android compat.
I'ma try to test it against android 3.1 (still have to download sdk)
If someone can test it on other versions/platforms, it would be greatly 
appreciated.

Cheers
```

Original comment by `david.yu...@gmail.com` on 7 Jul 2011 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
Woops forgot to attach the patch.

```

Original comment by `david.yu...@gmail.com` on 7 Jul 2011 at 10:05

Attachments:
- [android.diff](https://storage.googleapis.com/google-code-attachments/protostuff/issue-67/comment-11/android.diff)

**Comment by GoogleCodeExporter** [comment]
```
Hi David,
tried the patch on 2.3., but I am afraid it will need more work, specifically 
because of the line:
return sun.reflect.ReflectionFactory.getReflectionFactory()
                .newConstructorForSerialization(clazz, OBJECT_CONSTRUCTOR);
here the compiler won't find the sun.reflect.ReflectionFactory package on 
android.

Furthermore, If I may propose, use Android 2.1 (alternatively 2.2 or 2.3.3) as 
a testbed. Reason being the current fragmentation of the devices. Android 3.1 
is too bleeding-edge. See it here: 
http://developer.android.com/resources/dashboard/platform-versions.html.

Some words on current compatibility:
Android 1.6+: Protostuff 1.0.0 CORE/API works for me with the rough changes 
proposed in my initial post.

Android 2.3.3: With Issue  #58 already being resolved (and assuming #67 gets 
fixed), Protostuff 1.0.1 should be fine also including packages 
CollectionSchema/Runtime.

Android 2.1 - 2.2: Was not tested. Should behave be either as 1.6 (only 
core/api) or 2.3.3 (incl. Runtime).

One more thing: you're certainly aware, that the prebuilt JAR files are not 
usable on android (you get a LanguageException), so a maven target for android 
would be nice. I simply copied the necessary files over into my sources 
directory in eclipse. That did it for me, so if maven created the necessary 
directory structure to be copied into the eclipse project folder, that should 
be fine.
```

Original comment by `matyas.b...@gmail.com` on 7 Jul 2011 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Hi Matyas,

Thanks for testing.  I was able to test against android 3.1 (took me long 
enough).
RuntimeSchema worked fine . However it wont work if your pojos have final 
fields w/c effectively requires the deserialization to bypass the constructor.

ObjectInputStream.newInstance is no longer on 3.1 (and I believe 2.x as well).
If we can find out the new mechanism to bypass the constructor for 2.x to 3.x, 
it shouldn't be a problem.  Help will be needed to dig up the android source 
(basically apache harmony) and find a suitable replacement.
```

Original comment by `david.yu...@gmail.com` on 7 Jul 2011 at 5:06

**Comment by GoogleCodeExporter** [comment]
```
I am not sure if ObjectInputStream.newInstance is not on 3.1, but it is 
definitely there on 2.3.3  - I can obtain the method 'newInstance' without 
problems via reflection (checked on two different phones with 2.3.3 and also on 
the android emulator with 2.3.3)

```

Original comment by `matyas.b...@gmail.com` on 7 Jul 2011 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
BTW: 3.1 is not open-sourced yet, so we can't check. On 2.3.3 I can clearly see 
this method in the sources.
ObjectInputStream is in the the GIT repository of Android Open Source Project, 
under platform/libcore: 
http://android.git.kernel.org/?p=platform/libcore.git;a=summary

If you don't want to download the whole package, check it onLine here: 
http://www.java2s.com/Open-Source/Android/android-core/platform-libcore/java/io/
ObjectInputStream.java.htm
```

Original comment by `matyas.b...@gmail.com` on 7 Jul 2011 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
Matyas,

Yep you're right.  I can confirm that ObjectInputStream.newInstance is no 
longer available in 3.1 but is available in 2.x

sun.reflect.ReflectionFactory is not available on both 3.1 and 2.x.
sun.misc.Unsafe is available on 3.1 (not all methods are present though) but 
not on 2.x

So at the moment, only 3.1 will not work if bypassing the constructor is a 
requirement.

I'll push a commit in a few hours to address the issues above.
Thanks for doing tests.

Cheers
```

Original comment by `david.yu...@gmail.com` on 8 Jul 2011 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I've committed the fix for this @ rev 1336.
Was able to test on 2.3.3 emulator and it ran fine.
Matyas, if you can confirm that the fix works for you, that would be great.

If there are no longer issues, 1.0.1 will be released.
```

Original comment by `david.yu...@gmail.com` on 8 Jul 2011 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
How did you build it? It still throws errors for me on 
OnDemandSunReflectionFactory.java and RuntimeUnsafeFieldFactory.java

Eclipse does not allow it to build because of the missing packages 
sun.reflect.* and sun.misc.unsafe.
```

Original comment by `matyas.b...@gmail.com` on 8 Jul 2011 at 7:45

**Comment by GoogleCodeExporter** [comment]
```
The android project had a "lib" dir where I put the protostuff jars (directly 
copied from m2 repo, no mods).  Each jar is added to the android build path.
So when I run the android project (with the debugger), it uploaded to avd 
without any warnings/errors and ran fine.

I've attached the test project.

To be sure, you can delete OnDemandSunReflectionFactory.java and 
RuntimeUnsafeFieldFactory.java (both are optional) and apply this patch 
(attached).

I'll see if I can have this automated for a special android build.

```

Original comment by `david.yu...@gmail.com` on 9 Jul 2011 at 1:26

Attachments:
- [2.3.3.zip](https://storage.googleapis.com/google-code-attachments/protostuff/issue-67/comment-19/2.3.3.zip)
- [runtime4android.patch](https://storage.googleapis.com/google-code-attachments/protostuff/issue-67/comment-19/runtime4android.patch)

**Comment by GoogleCodeExporter** [comment]
```
I've added a protostuff-runtime-md module w/c addresses the issues you pointed 
out.
Please let me know if you're still getting errors.

Cheers
```

Original comment by `david.yu...@gmail.com` on 9 Jul 2011 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
I see now how you did it. It works now with the libs.
With version 1.0 when tried to use the libs I got the LanguageException error, 
so I figured I have to have Eclipse compile them manually ( most probably it 
was because issue #58 and this). Good job David.
The automated build for android would be great. Are there any "conditional 
compiler statements" in java just like in C (#IF, #ELSE)?
```

Original comment by `matyas.b...@gmail.com` on 9 Jul 2011 at 7:35

**Comment by GoogleCodeExporter** [comment]
```
Cool.
The automated build is protostuff-runtime-md (w/c just imports the files from 
protostuff-runtime and replaces the necessary parts).
Was it protostuff-runtime-md that you tested or the vanilla protostuff-runtime?

PS. I dont think there are any conditional compiler statements in java.

Cheers
```

Original comment by `david.yu...@gmail.com` on 9 Jul 2011 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
I tested the vanilla libs - the ones you had in your project.
```

Original comment by `matyas.b...@gmail.com` on 9 Jul 2011 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
Alright.  I'm closing this issue.

Thanks for your help :-)
```

Original comment by `david.yu...@gmail.com` on 9 Jul 2011 at 8:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
By the way, one remark how you solved the Android compatibility with the 
constructor. Wouldn't it be nicer to have an abstract interface (for the 
different factories), have all classes (Unsafe, standard reflection and 
android) implement them, and then just call them with Class.forName(String), 
etc? IMHO, interfaces for this would make the code much more readable.
```

Original comment by `matyas.b...@gmail.com` on 9 Jul 2011 at 8:17
