### ISSUE TITLE
IllegalArgumentException thrown when instantiating a non-public class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hanson-opus/protostuff#94]
```
What steps will reproduce the problem?
1. Try to deserialize an object containing a field of type 
javax.xml.datatype.XMLGregorianCalendar.

byte[] protocolBuffer = ProtostuffIOUtil.toByteArray(response, RESPONSE_SCHEMA, 
LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE)); // Seems to work.

Object r = new Object(); // Object w XMLGregorianCalendar type.
ProtostuffIOUtil.mergeFrom(protocolBuffer, r, RESPONSE_SCHEMA); // Fails here.



What is the expected output? What do you see instead?

A Java object with all previously serialized data is expected

instead the following exception is thrown:

java.lang.RuntimeException: java.lang.IllegalAccessException: Class 
com.dyuproject.protostuff.runtime.RuntimeEnv$DefaultInstantiator can not access 
a member of class org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl with 
modifiers "public"
    at com.dyuproject.protostuff.runtime.RuntimeEnv$DefaultInstantiator.newInstance(RuntimeEnv.java:216)
    at com.dyuproject.protostuff.runtime.RuntimeSchema.newMessage(RuntimeSchema.java:346)
    at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$14$1.doMergeFrom(RuntimeUnsafeFieldFactory.java:854)
    at com.dyuproject.protostuff.runtime.RuntimeDerivativeField$1.doMergeFrom(RuntimeDerivativeField.java:53)
    at com.dyuproject.protostuff.runtime.DerivativeSchema.mergeFrom(DerivativeSchema.java:93)
    at com.dyuproject.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:390)
    at com.dyuproject.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:362)
    at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$14$1.mergeFrom(RuntimeUnsafeFieldFactory.java:829)
    at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:188)
    at com.dyuproject.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:390)
    at com.dyuproject.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:362)
    at com.dyuproject.protostuff.runtime.RuntimeRepeatedFieldFactory$3.mergeFrom(RuntimeRepeatedFieldFactory.java:199)
    at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:188)
    at com.dyuproject.protostuff.IOUtil.mergeFrom(IOUtil.java:43)
    at com.dyuproject.protostuff.ProtostuffIOUtil.mergeFrom(ProtostuffIOUtil.java:96)



What version of the product are you using? On what operating system?
Version 1.0.4 on Windows XP

Please provide any additional information below.
```

Original issue reported on code.google.com by `jeff.j.b...@gmail.com` on 10 Nov 2011 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Is this expected?  Is there a workaround?
```

Original comment by `jeff.j.b...@gmail.com` on 10 Nov 2011 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
Can you attach the self-contained test so I can check?
```

Original comment by `david.yu...@gmail.com` on 11 Nov 2011 at 8:07
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
So I copied the code out of my application into a mini project, and it works.

Still haven't been able to figure out why it doesn't work inside the primary 
app.

I'll post back with my findings.
```

Original comment by `jeff.j.b...@gmail.com` on 11 Nov 2011 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
Okay, found it.

Turns out if your project depends on the xercesImpl.jar, the 
XMLGregorianCalendar implementation is switched to the xerces version.

On that specific implementation protostuff chokes, and throws the above error.

I have attached a maven project that will replicate the problem if you run the 
main method within the Bug.java class.
```

Original comment by `jeff.j.b...@gmail.com` on 11 Nov 2011 at 6:19

Attachments:
- [protostuff-xmlcal-bug.zip](https://storage.googleapis.com/google-code-attachments/protostuff/issue-94/comment-4/protostuff-xmlcal-bug.zip)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the test case.
The expeption is thrown because the XMLGregorianCalendar impl's class was not 
public.
```

Original comment by `david.yu...@gmail.com` on 12 Nov 2011 at 1:37
- Changed title: **IllegalArgumentException thrown when instantiating a non-public class**
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
fixed @ rev 1429.
Thanks again for the maven test-case
```

Original comment by `david.yu...@gmail.com` on 12 Nov 2011 at 1:38
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick fix.  Appreciated.  Look forward to working more with your 
API.
```

Original comment by `jeff.j.b...@gmail.com` on 13 Nov 2011 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
How was this issue fixed? I am facing the same issue. Please help.
```

Original comment by `nobodykn...@gmail.com` on 22 Jun 2015 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
How was this issue fixed? I am facing the same issue. Please help.
```

Original comment by `nobodykn...@gmail.com` on 22 Jun 2015 at 8:35
